### PR TITLE
Fix for https://github.com/redstone-dart/redstone/issues/190

### PR DESCRIPTION
**Pull request by stijnvanbael**
Fix for https://github.com/redstone-dart/redstone/issues/190 (Stacktraces are logged on severe for 400 range response codes)

### CODE REVIEW

**Comment by Pacane** [comment]
Thanks a lot!

**Comment by Pacane** [comment]
Do you think you could write a test in the router tests to cover this case?

**Comment by stijnvanbael** [comment]
I updated the 400 and 500 error tests to check the logging.

**Review by Pacane — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
