### PR TITLE
Don't parse body with certain methods.

### LINKED ISSUE #131: http_body_parser tries to parse body of GET Requests
I just found out that http_body_parser tries to parse the body of every request if the header 'Content-Type' is set to 'application/json'. If the request is GET this obviously fails because GET requests dont have a body.

Stack trace of the error:
Failed to execute .getDays - FormatException: Unexpected end of input (at character 1)

^

dart:convert                                       JsonCodec.decode
package:redstone/src/http_body_parser.dart 101:60  _parseRequestBody.<fn>

### PR DESCRIPTION
**Pull request by TheBosZ**
Fixes #131

### CODE REVIEW

**Comment by Pacane** [comment]
Thanks for the contribution! But would you mind adding a test for this case? I'm trying to add tests for everything I touch now.

Please :)

**Comment by TheBosZ** [comment]
I can't get it to error when I'm doing it in testing. Only when doing a real request.
Have any ideas?

**Comment by Pacane** [comment]
Can you show me the code of your test?

**Comment by TheBosZ** [comment]
I just pushed my changes. I was testing the old behavior by just setting `RequestParser._skipParseOnMethods` to `[]`

**Comment by Pacane** [comment]
Alright! Thanks for the contribution! :) I'll see to make a release off that.

**Pull request merged**
